apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-cluster-read-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster-read-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: default-cluster-read-role
  apiGroup: rbac.authorization.k8s.io