apiVersion: v1
kind: ConfigMap
metadata:
  name: ft-tracker-config
  labels:
    spring.cloud.kubernetes.config: "true"
data:
  application.yaml: |-
    demo:
      reloadingMsg: 'Working RS'
    finance-tracker:
      cors-origins: 'http://financetracker:4200'
      async:
        corePoolSize: 5
        maxPoolSize: 20
        queueCapacity: 1000
      jwt:
        authorities: authorities
        secret: f8fc53e7ce78d1dcc40abe520ca0470dc023d41f6a77fc2679b09dda47a0d6b6