logging:
  level:
    org.spring: debug

server:
  port: 8090
  servlet:
    contextPath: /api
spring:
  application:
    name: finance_tracker_service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:db/changelog/master.xml