spring:
  datasource:
    url: jdbc:postgresql://localhost:30543/finance_tracker
    username: postgres
    password: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost/auth/realms/finance-tracker

management:
  endpoints:
    web:
      exposure:
        include: "*"
