logging:
  level:
    com.tracker: debug

server:
  port: 8090
  servlet:
    contextPath: /api
spring:
  application:
    name: finance-tracker-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/master.xml
