jwt:
    authorities:
        key: auth
    secret:
        key: asfd
logging:
    level:
        org.spring: debug

server:
    port: 8090
    servlet:
        contextPath: /api
spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/finance_tracker
        username: postgres
        password: admin
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
                format_sql: true
                temp:
                    use_jdbc_metadata_defaults: false
        open-in-view: false
    liquibase:
        change-log: classpath:db/changelog/master.xml