spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/finance_tracker
    username: postgres
    password: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/finance-tracker

finance-tracker:
  cors-origins: 'http://financetracker:4200'
  async:
    corePoolSize: 5
    maxPoolSize: 20
    queueCapacity: 1000
  jwt:
    authorities: authorities
    secret: f8fc53e7ce78d1dcc40abe520ca0470dc023d41f6a77fc2679b09dda47a0d6b6
