logging:
  level:
    com.tracker: debug

server:
  port: 8090
  shutdown: GRACEFUL

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/master.xml


finance-tracker:
  cors-origins: 'http://localhost:4200'
  async:
    corePoolSize: 5
    maxPoolSize: 20
    queueCapacity: 1000
  jwt:
    authorities: authorities
    secret: f8fc53e7ce78d1dcc40abe520ca0470dc023d41f6a77fc2679b09dda47a0d6b6
