jwt:
    authorities:
        key: auth
    secret:
        key: asfd
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor: TRACE
server:
    port: 8090
    servlet:
        contextPath: /api
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/finance_tracker?useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
    liquibase:
        change-log: classpath:src/src/main/resources/db/changelog/master.xml
