spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/finance_tracker
    username: postgres
    password: admin

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

jwt:
  authorities:
    key: auth
  secret:
    key: f8fc53e7ce78d1dcc40abe520ca0470dc023d41f6a77fc2679b09dda47a0d6b6
