spring:
  datasource:
    url: jdbc:postgresql://localhost:30543/idp
    username: postgres
    password: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost/auth/realms/finance-tracker
