logging:
  level:
    com.tracker: debug

server:
  port: 8082
  shutdown: GRACEFUL

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  mvc:
    problemdetails:
      enabled: true
    throw-exception-if-no-handler-found: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/master.xml
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: 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
    protocol: smtp
    properties.mail.smtp:
      mail:
        trnsport: smtp
        smtp:
          auth: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

auth:
  client:
    client-id: finance-tracker
    client-secret: finance-tracker
    grant-types: password, authorization_code, refresh_token
    scope: openid, read, write, trust
  jwt:
    validity: 30m
    refresh-validity: 30d

idp:
  ft-ui: http://localhost:8082
  token-type-to-validity:
    reset: 24h
    verification: 48h
  previous-passwords-limit: 10
  login-attempts-limit: 3
  async:
    corePoolSize: 5
    maxPoolSize: 20
    queueCapacity: 1000
  mail:
    from: finance.tracker.test@gmail.com
    email: FinanceTracker
