logging:
  level:
    org.spring: debug

server:
  port: 8082
spring:
  application:
    name: auth_service

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

auth:
  client:
    client-id: finance-tracker
    client-secret: finance-tracker
    grant-types: password, authorization_code, refresh_token
    scope: read, write, trust
