logging:
  level:
    com.tracker: debug

server:
  port: 8082
spring:
  application:
    name: auth_service
  datasource:
    url: jdbc:postgresql://localhost:5432/idp
    username: postgres
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/master.xml

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

auth:
  client:
    client-id: finance-tracker
    client-secret: finance-tracker
    grant-types: password, authorization_code, refresh_token
    scope: openid, read, write, trust
  jwt:
    validity: 30m
    refresh-validity: 30d
