spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/idp
    username: postgres
    password: admin

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
