server:
    port: 8090
    servlet:
        contextPath: /api
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/finance_tracker
        password: admin
        username: admin
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQL9Dialect
            format_sql: true
            temp:
            use_jdbc_metadata_defaults: false
        open-in-view: false
    liquibase:
        change-log: classpath:db/changelog/master.xml
logging:
    level:
        org.spring: debug
jwt:
    authorities:
        key: auth
    secret:
        key: asfd
