server:
  port: 4000

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER:localhost:8761}/eureka/
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
#logging:
#  level:
#    org:
#      springframework:
#        cloud.gateway: DEBUG
#        http.server.reactive: DEBUG
#        web.reactive: DEBUG

spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8095/auth/realms/finance-tracker
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ft-api-gateway
            client-secret: 51dbbc86-c79f-4f90-becc-b9556fed6729
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8095/auth/realms/finance-tracker
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay
      routes:
        - id: uaa-service
          uri: lb://uaa-service
          predicates:
            - Path=/uaa/**
          filters:
            - RewritePath=/uaa/(?<path>.*), /$\{path}
        - id: finance-tracker-service
          uri: lb://finance-tracker-service
          predicates:
            - Path=/ft/**
          filters:
            - RewritePath=/ft/(?<path>.*), /$\{path}
