server:
  port: 4000

#eureka:
#  client:
#    registryFetchIntervalSeconds: 5
#    serviceUrl:
#      defaultZone: http://${DISCOVERY_SERVER:localhost:8761}/eureka/
#    healthcheck:
#      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost/auth/realms/finance-tracker
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ft-api-gateway
            client-secret: 51dbbc86-c79f-4f90-becc-b9556fed6729
      resourceserver:
        jwt:
          issuer-uri: http://localhost/auth/realms/finance-tracker
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay
      routes:
        - id: uaa-service
          uri: lb://uaa-service
          predicates:
            - Path=/uaa/**
          filters:
            - RewritePath=/uaa/(?<path>.*), /$\{path}
        - id: finance-tracker-service
          uri: lb://finance-tracker-service
          predicates:
            - Path=/ft/**
          filters:
            - RewritePath=/ft/(?<path>.*), /$\{path}
