server:
  port: 4000
  shutdown: GRACEFUL

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost/auth/realms/finance-tracker
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ft-api-gateway
            client-secret: 51dbbc86-c79f-4f90-becc-b9556fed6729
      resourceserver:
        jwt:
          issuer-uri: http://localhost/auth/realms/finance-tracker
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: false #false when using K8s discovery
          lower-case-service-id: true
      default-filters:
        - TokenRelay
      routes:
        - id: uaa-service
          uri: lb://uaa-service
          predicates:
            - Path=/uaa/**
          filters:
            - RewritePath=/uaa/(?<path>.*), /$\{path}
        - id: finance-tracker-service
          uri: lb://finance-tracker-service
          predicates:
            - Path=/ft/**
          filters:
            - RewritePath=/ft/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
#  enable-native-support: true
#  api-docs:
#    groups:
#      enabled: true
#    enabled: true
#  group-configs:
#    - group: api-gateway
#      packages-to-scan:
#        - com.tracker
#      display-name: API Gateway
#    - group: ft-service
#      paths-to-match:
#        - /ft-service/**
#      display-name: Characters Service
  swagger-ui:
#    config-url: /v3/api-docs/swagger-config
#    url: /v3/api-docs
    urls:
      - name: uaa-service
        url: /v3/api-docs/uaa
      - name: finance-tracker-service
        url: /v3/api-docs/ft