server:
  port: 4000

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER:localhost:8761}/eureka/
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info

spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          uaa:
            client-id: finance-tracker
            client-secret: finance-tracker
            authorization-grant-type: authorization_code
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
            clientName: gateway
        provider:
          uaa:
            authorization-uri: http://localhost:8082/oauth/authorize
            token-uri: https://localhost:8082/oauth/token
            jwt-key-uri: http://localhost:8082/oauth/token_key
            userNameAttribute: user_name
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: uaa-service
          uri: lb://uaa-service
          predicates:
            - Path=/uaa/**
          filters:
            - RewritePath=/uaa/(?<path>.*), /$\{path}
            - TokenRelay=
        - id: finance-tracker-service
          uri: lb://finance-tracker-service
          predicates:
            - Path=/ft/**
          filters:
            - RewritePath=/ft/(?<path>.*), /$\{path}
            - TokenRelay=
  #            - PreOauth2SSOGatewayFilter
