version: '3.7'
services:
  postgres:
    image: 'postgres:11-alpine'
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: finance_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - ft-network
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8095:8080
    depends_on:
      - postgres
    networks:
      - ft-network
  discovery:
    image: 'discovery:latest'
    container_name: discovery
    ports:
      - 8761:8761
    networks:
      - ft-network
  gateway:
    image: 'gateway:latest'
    ports:
      - 4000:4000
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DISCOVERY_PORT: 8761
      DISCOVERY_SERVER: discovery:8761
    depends_on:
      - discovery
    networks:
      - ft-network
  uaa-service:
    image: 'uaa-service:latest'
    ports:
      - 8082
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DISCOVERY_PORT: 8761
    depends_on:
      - postgres
      - discovery
    networks:
      - ft-network
  finance-tracker-service:
    image: 'finance-tracker-service:latest'
    ports:
      - 8090
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_PORT: 5432
    depends_on:
      - postgres
      - discovery
    networks:
      - ft-network

networks:
  ft-network:

volumes:
  db-data:
    driver: local
