apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-tracker-service
  labels:
    app: finance-tracker-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-tracker-service
  template:
    metadata:
      labels:
        app: finance-tracker-service
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        image: finance-tracker-service:latest
        imagePullPolicy: IfNotPresent
        name: finance-tracker-service
        ports:
          - containerPort: 8090
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: finance-tracker-service
  name: finance-tracker-service
spec:
  selector:
    app: finance-tracker-service
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30090
  type: NodePort
