apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uaa-service
  name: uaa-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uaa-service
  template:
    metadata:
      labels:
        app: uaa-service
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        image: uaa-service:latest
        imagePullPolicy: IfNotPresent
        name: uaa-service
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: uaa-service
  name: uaa-service
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: uaa-service

