apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env
  labels:
    app: keycloak
data:
  KC_DB: "postgres"
  KC_DB_URL: {{ .Values.keycloak.db.url | quote }}
  KC_DB_USERNAME: {{ .Values.keycloak.db.username | quote }}
  KC_DB_PASSWORD: {{ .Values.keycloak.db.password | quote }}
  KC_HEALTH_ENABLED: "true"
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.keycloak.admin.username | quote }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password | quote }}
