apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  labels:
    app: keycloak
data:
  {{- range $path, $_ := .Files.Glob "files/*.json" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{- end }}
