#Workflow name
name: build-test

on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    paths:
      - "gateway/**"
      - ".github/workflows/gateway.yaml"

jobs:

  build-parent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --file pom.xml -pl '-gateway,-discovery,-uaa-service,-finance-tracker-service' clean install

  # This workflow contains a single job called "test"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORK_SPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Run Tests
        run: |-
          cd .\gateway
          mvn test